[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "22"

[build]
  publish = "examples/dist"
  command = "pnpm run -C examples build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
