[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "22"

[build]
  publish = "dist"
  command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run build && npx pnpm run examples"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
